CREATE OR REPLACE TRIGGER TRG_AUDIT_CONNECTION
AFTER LOGON ON DATABASE
BEGIN
  FOR X IN (SELECT USERS.USERNAME,
                   USERS.PROFILE,
                   SESSIONS.RESOURCE_CONSUMER_GROUP,
                   CASE
                     WHEN USERS.PROFILE LIKE 'ORA%' OR PROFILE LIKE 'DEFAULT' THEN
                      'ADW_HIGH, ADW_MEDIUM, ADW_LOW'
                     WHEN USERS.PROFILE LIKE 'PFL_POWERUSER' THEN
                      'ADW_LOW, ADW_MEDIUM'
                     WHEN USERS.PROFILE LIKE 'PFL_FINALUSER' THEN
                      'ADW_LOW'
                   END SERVICES_ALLOWED
              FROM SYS.V_$SESSION SESSIONS
              JOIN SYS.DBA_USERS USERS
                ON SESSIONS.USERNAME = USERS.USERNAME
             WHERE AUDSID = USERENV('SESSIONID')) LOOP
    IF (INSTR(X.SERVICES_ALLOWED, X.RESOURCE_CONSUMER_GROUP) = 0) THEN
      RAISE_APPLICATION_ERROR(-20999,'Unauthorized connection. Please use services names allowed: ' || X.SERCICES_ALLOWED);
    END IF;
  END LOOP;
END TRG_AUDIT_CONNECTION;
/
